const MESSAGE_TYPES = {
    KNOB_COLOR: 0,
    KNOB_TYPE: 1,
    KNOB_CC_TYPE: 2,
    KNOB_MIDI_CHANNEL: 3,
    KNOB_MIDI_CC1: 4,
    KNOB_MIDI_CC2: 5,
    BANK_COLOR: 50,
    BANK_SNAPSHOT_COLOR: 51,
    BRIGHTNESS: 100,
    FIRMWARE_UPLOAD: 125,
    FIRMWARE_VERSION: 126,
    SYNC: 127,
};

module.exports = MESSAGE_TYPES;